language: rust
os:
- linux
- osx
rust:
- nightly
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
deploy:
  provider: releases
  api_key:
    secure: Uw6eBYE2TKqf2nqPW+rQReFrKcv48bpJMPntT16P4K/86ZA9NATlK85gg9ilqoPnOqkqfxKKWbw4/WsgCngaadty7cZZboq6foz3CFtoQs/DFJOqdURmlVgS+ApaOeT9UjsmJcJzPyiMldLT4ucEQqVmM183hWQmphEBCC5Xoc8pMh+gq3j3RT0YwW+jbnDY8zBlAdqDaYT6qB4pD66eu4vv1FeGNjCOeD5Meq3O8b953lBA3U4jlutDiAcTCHDWnfJjdEdK5qnwIZ23OmbYKZllLWrenQ+hIfOa6HYrnq8AatfXjY0ctnApxfp3P8FzLIsduDvscBjZTSl51V8sNHhN6WMWxkvGmCeKF84McpBhZTmPx0VNQdjTpg0u3cU1RZVq5IMIP6y6b5VXkU71fG69X0JbLKAWhIP7k5FkMwtokV8UCjFWaEQ7gRFrtmmHWMTTbUw8UIOsW2fuWdDiX7N7/IY6Aq09K4r2O4k16OldWn2NrucOMZkb5cB1ZNd3163So/j01MdSGsO6klE1jcFYX3/BE9+Gc8O9Ey4soxblWIfhT+8QiAi4zB5hgrcDwZhAZ5D6M1IjsGB7OymjgqykuO7t2JPFGbW1sLVftqveOapeyFNZtq9Yx++nyySQtzTAyOdgZiTiWF+oWWGeITUyrYDOBfWcaTEVc+8Hx2g=
  file: target/debug/navkafka-cli
  skip_cleanup: true
  on:
    tags: true
